FROM ros:foxy
LABEL maintainer="bernd.pfrommer@gmail.com"
LABEL version="1.0"
LABEL description="enriched foxy image"
ARG DEBIAN_FRONTEND=noninteractive
ARG ROS2_VERSION=foxy

RUN sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys AD19BAB3CBF125EA
RUN apt-get -y update
# RUN apt-get -y dist-upgrade

# extra ROS packages
RUN apt-get -y install python3-osrf-pycommon ros-${ROS2_VERSION}-image-transport ros-${ROS2_VERSION}-cv-bridge ros-${ROS2_VERSION}-sensor-msgs ros-${ROS2_VERSION}-std-msgs ros-${ROS2_VERSION}-rosbag2 ros-${ROS2_VERSION}-rosbag2-cpp ros-${ROS2_VERSION}-tf2-ros ros-${ROS2_VERSION}-image-geometry ros-${ROS2_VERSION}-tf2-geometry-msgs ros-${ROS2_VERSION}-camera-info-manager ros-${ROS2_VERSION}-ament-cmake-clang-format ros-${ROS2_VERSION}-ament-cmake-*

# git, clang-tidy, colcon, vcs tool
RUN apt-get -y install git clang-tidy python3-vcstool libopencv-dev 

# needed for basalt
RUN apt-get -y install libfmt-dev libbz2-dev ros-${ROS2_VERSION}-ament-cmake-clang-format

# needed for ffmpeg_image_transport
RUN apt-get -y install libavcodec-dev libswresample-dev libswscale-dev libavutil-dev libavdevice-dev libavfilter-dev libavformat-dev

# OpenEB dependencies
RUN apt-get -y install apt-utils build-essential software-properties-common wget unzip curl git cmake libopencv-dev libboost-all-dev libusb-1.0-0-dev libhdf5-dev hdf5-tools libglew-dev libglfw3-dev libcanberra-gtk-module ffmpeg 


# various handy development tools
RUN apt-get -y install tmux emacs magit elpa-markdown-mode virtualenvwrapper xterm inetutils-tools net-tools strace sudo udev usbutils

# create sudo-privileged user but this somehow doesn't really work.
# Connect to the container as root instead.

RUN apt-get -y install sudo
RUN useradd -u 1000 -m pfrommer -G sudo -s /usr/bin/bash && echo "pfrommer:foo" | chpasswd && adduser pfrommer sudo