FROM berndpfrommer/focal_noetic
LABEL maintainer="bernd.pfrommer@gmail.com"
LABEL version="1.0"
LABEL description="ubuntu focal with ROS noetic and dev environment"
ARG DEBIAN_FRONTEND=noninteractive
ARG SILKY_VERSION=4.1.0
RUN apt-get update


#
# add gtsam (for tagslam)
#

RUN apt-add-repository ppa:borglab/gtsam-release-4.1
RUN apt-get update && apt-get -y install libgtsam-dev libgtsam-unstable-dev

#
# install various development tools 
#
RUN apt-get -y install tmux emacs magit elpa-markdown-mode virtualenvwrapper xterm
RUN apt-get -y install inetutils-tools net-tools strace

#
# more ROS packages
#

RUN apt-get -y install ros-noetic-rqt-bag ros-noetic-rqt-bag-plugins ros-noetic-rqt-image-view ros-noetic-rviz ros-noetic-image-transport-codecs ros-noetic-image-transport-plugins

#
# hugo, for my personal web page
#

RUN apt-get -y install hugo

#
# OpenEB dependencies
#

RUN apt-get -y install apt-utils build-essential software-properties-common wget unzip curl git cmake
RUN apt-get -y install libopencv-dev libboost-all-dev libusb-1.0-0-dev
RUN apt-get -y install libhdf5-dev hdf5-tools libglew-dev libglfw3-dev libcanberra-gtk-module ffmpeg 

#
# SilkyEvCam tools and plugins
#
RUN apt-get -y install usbutils udev
COPY SilkyEvCam_Plugin_Installer_for_ubuntu_v${SILKY_VERSION}.zip .
RUN unzip ./SilkyEvCam_Plugin_Installer_for_ubuntu_v${SILKY_VERSION}.zip
RUN cd ./SilkyEvCam_Plugin_Installer_for_ubuntu_v${SILKY_VERSION}/SilkyEvCam_Plugin_Installer_for_ubuntu_v${SILKY_VERSION} && chmod a+x ./CA_Silky_installer.sh && ./CA_Silky_installer.sh; exit 0


#
# cura
#
COPY cura-lulzbot-3.6.40-deb10-Linux.deb .
COPY libreadline7_7.0-3_amd64.deb .
RUN apt-get -y install ./libreadline7_7.0-3_amd64.deb
RUN apt-get -y install libgl1-mesa-glx libtinfo5
RUN apt-get -y install ./cura-lulzbot-3.6.40-deb10-Linux.deb
#
# create a pfrommer user with sudo privileges and poor password
#
RUN apt-get -y install sudo
RUN useradd -u 1000 -m pfrommer -G sudo -s /usr/bin/bash && echo "pfrommer:foo" | chpasswd && adduser pfrommer sudo
